server:
  port: 8080
  mode: debug  # debug or release
  read_timeout: 60
  write_timeout: 60

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: blog
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 100

log:
  level: debug
  filename: ./logs/app.log
  max_size: 100    # megabytes
  max_age: 30      # days
  max_backups: 7
  compress: true

jwt:
  secret: your-secret-key
  expire: 24h      # token expiration time
  issuer: blog-api 